### ISSUE TITLE
API not up-to-date with Dialogflow Console

### ISSUE THREAD

**Issue by hackthedev** [googleapis/nodejs-dialogflow#911]
Hi so my issue is simple.

I used the smalltalk agent and added it, implemented it into my discord.js bot, updated some stuff again, but now it is working, but its not updated. It works in the Dialogflow Console on the website but doesnt work via api on my discord bot, only the old intents etc when first implementing it.

How can I fix this? I found no solution, re-saving or re-training didnt work eighter.

**Comment by galz10** [comment]
Hi @hackthedev how does your discord bot connect to the agent ?

**Comment by hackthedev** [comment]
Hi yes it does and it works with the smalltalk premade agent and i tried adding new intents etc but it wont work it acts like i never updated and added intents

**Comment by galz10** [comment]
okay, what code does your discord bot use to connect to the dialogflow agent ?

**Comment by hackthedev** [comment]
I use this code -> https://pastebin.com/stLN09G8
Basically the only important function is "reply()" since this is the part where i try to connect to the agent, which works, but only with the old data somehow

**Comment by galz10** [comment]
Yea this is strange, and i'm guessing you're testing the same phrases that you test in the console in discord correct ? and are you getting any errors from the detect intent call ?

**Comment by hackthedev** [comment]
Hi so when i insults on the web console it works perfectly it detects the intent etc when i do it in discord it is unable to detect the intent and goes for the default fallback intent saying something like "sorry i didnt get that".

Here is the web demo https://bot.dialogflow.com/fc8ca23f-6228-430c-be99-66ee663d2c94
If you say something like for example "fuck you" cauz i wanted to handle insults it will respond to it. on discord it will not detect it. there are no errors it just doesnt detect it like if that intent never existed

**Comment by galz10** [comment]
So i ran your code and i believe the issue is with your code. Once i fixed the code i got the intents i expected. 
So for when importing dialogflow you should use `const dialogflow = require('@google-cloud/dialogflow')` instead of what you have and there is no `sessionPath` function in Node so you'll need to change it to `projectAgentSessionPath`

i edited the parts of the code below to show you the difference. 

``` async function reply(message, text) {
    message.channel.startTyping();
 
    // Example code from the Dialogflow Node.js library:
    // https://github.com/googleapis/nodejs-dialogflow
    const dialogflow = require('@google-cloud/dialogflow');
    const uuid = require('uuid');
 
    // A unique identifier for the given session
    const sessionId = uuid.v4();
    const key = JSON.parse(JSON.stringify(testkey));
 
    // Creates a session client from a Google service account key.
    const sessionClient = new dialogflow.SessionsClient({
        projectId: key.project_id,
        credentials: {
            client_email: key.client_email,
            private_key: key.private_key,
        }
    });
 
    const sessionPath = sessionClient.projectAgentSessionPath(key.project_id, sessionId);
 ```

**Comment by hackthedev** [comment]
Hi so i changed the code to the following code below but its still not working.

Code:
```
async function reply(message, text) {
    const testkey = require("./key.json");

    message.channel.startTyping();

    // Example code from the Dialogflow Node.js library:
    // https://github.com/googleapis/nodejs-dialogflow
    const dialogflow = require('@google-cloud/dialogflow');
    const uuid = require('uuid');

    // A unique identifier for the given session
    const sessionId = uuid.v4();
    const key = JSON.parse(JSON.stringify(testkey));

    // Creates a session client from a Google service account key.
    const sessionClient = new dialogflow.SessionsClient({
        projectId: key.project_id,
        credentials: {
            client_email: key.client_email,
            private_key: key.private_key,
        }
    });

    const sessionPath = sessionClient.projectAgentSessionPath(key.project_id, sessionId);

    // The text query request.
    const request = {
        session: sessionPath,
        queryInput: {
            text: {
                // The query to send to the dialogflow agent
                text: text,
                // The language used by the client (en-US)
                languageCode: 'en-US',
            },
        },
    };

    // Send request and log result
    const responses = await sessionClient.detectIntent(request)
    console.log('Detected intent')
    const result = responses[0].queryResult
    console.log(`Query: ${result.queryText}`)
    console.log(`Response: ${result.fulfillmentText}`)

    message.channel.stopTyping();
    message.channel.send(result.fulfillmentText);

    if (result.intent) {
        console.log(`Intent: ${result.intent.displayName}`)
    } else {
        console.log(`No intent matched.`)
    }
}
```

Query output:
`Detected intent
Query: fuck you ciel
Response: I didn't get that. Can you say it again?
Intent: Default Fallback Intent
`

**Comment by galz10** [comment]
That's interesting this is working for me, are you sure the correct agent is trained and you're providing the correct project id ?

**Comment by hackthedev** [comment]
This is what it looks like for me
![image](https://user-images.githubusercontent.com/40896559/148270659-67dd5e7b-c766-46d1-82b2-0cb0a1c85d08.png)

I somehow get an error everytime for an agent i have already deleted as you can see here
![image](https://user-images.githubusercontent.com/40896559/148270745-cee526bd-6f56-44cf-a9ab-9ec9f2903808.png)

This is the agent i want to use 
![image](https://user-images.githubusercontent.com/40896559/148270794-a07f8307-59ce-4deb-9806-179dcaf97b1f.png)

The key.json file i use for auth also includes the correct project name `"project_id": "ciel-small-talk-cdei",`

I have also setup the key in the cloud platform 
![image](https://user-images.githubusercontent.com/40896559/148271667-f499c38d-677f-4a07-8d21-88bee1380520.png)
![image](https://user-images.githubusercontent.com/40896559/148271780-87ce0785-7e0d-4b9f-b729-6f0645ba0f4d.png)

This would be my custom intent thats not being found somehow
![image](https://user-images.githubusercontent.com/40896559/148272394-35dd89e0-45c8-445f-80c0-2b39a023159e.png)


i dont know what else i would be missing

**Comment by galz10** [comment]
So i think the agent you've delete is the agent you're seeing in the picture with the intents, i don't know why its not deleted but my hunch is you might have changed the agent you've deleted and that's why the `bad-word` intent isn't showing up

**Comment by hackthedev** [comment]
Maybe but the strange thing is its the only agent i have so i can only get the data from this agent right?
![image](https://user-images.githubusercontent.com/40896559/148490538-736566be-4a99-4b85-a55f-5d05c995412b.png)

When i go to the cloud console i still have all the projects i've ever created
![image](https://user-images.githubusercontent.com/40896559/148490745-eeab2427-4356-41f2-82a9-d9b5cf847e48.png)

**Comment by galz10** [comment]
What is the url for the first image ?

**Comment by hackthedev** [comment]
First image url is https://dialogflow.cloud.google.com/#/agents

I do get the same error message for the deleted agent on this url https://dialogflow.cloud.google.com/#/agent/ciel-small-talk-cdei/intents

**Comment by galz10** [comment]
Does the url have the # in it or are the # the project id ?

**Comment by hackthedev** [comment]
On the google console it looks like this:
https://console.cloud.google.com/home/dashboard?project=ciel-small-talk-cdei

And in dialogflow like this
https://dialogflow.cloud.google.com/#/editAgent/ciel-small-talk-cdei/

if that is what you mean


By the way i dont know about you but if you want to discuss this on discord for convenience my tag would be "Shy Devil#0001". Just in case.

**Comment by galz10** [comment]
if you go to `https://dialogflow.cloud.google.com/#/newAgent` in the select project dropdow, is  `ciel-small-talk-cdei` present in the list?

**Comment by hackthedev** [comment]
No its actually not i only have these projects listed 
![image](https://user-images.githubusercontent.com/40896559/149017151-7c3e255c-a521-41e6-b9d2-15740b510f55.png)

**Comment by galz10** [comment]
okay thats good it shouldn't be there if you have an agent. i might have already asked this but are you sure `key.project_id` is the correct project id ? The last thing is would be to export your agent to a zip and then import it into another project and see if that works.

**Comment by hackthedev** [comment]
yeah key file is correct as well as its contents. I will try exporting and reimporting it into another project. I will report back if it worked or not

**Comment by galz10** [comment]
did exporting the agent and import it on a different gcp project work ?Also i thought the intent that was giving you issues is the bad word intent, do all intents other then the default (`I didn't get that. Can you say it again?`) not work

**Comment by hackthedev** [comment]
Hi so the bad words intent is the smalltalk.agent.insult. this was the one i custom created. i exported it and imported it into another google project that was already existing. 

All the other intents work its only the *.*.insult one thats not working

**Comment by galz10** [comment]
that's weird i don't see why this doesn't work, on my end the intents work fine. Are you sure you have your agent trained and everything ? You could also create another intent that's similar and see if that works.

**Comment by hackthedev** [comment]
alright so i got it all to work now by resetting the agent and not using the "Prebuild Agent" feature "Smalltalk". I basically started doing all the intents myself and now it all works.

seems like the prebuild agent doesnt like new intents

**Comment by galz10** [comment]
okay i'll make a note of that thanks for letting me know.
